"""empty message

Revision ID: 41751f48a4df
Revises: 45e4d3c227fd
Create Date: 2015-01-14 23:26:12.392465

"""

# revision identifiers, used by Alembic.
revision = '41751f48a4df'
down_revision = '45e4d3c227fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikeusages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('style', sa.Integer(), nullable=True),
    sa.Column('terrain', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('cleaning', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.Integer(), nullable=True),
    sa.Column('gears', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bikeusages')
    ### end Alembic commands ###
